# Filtering dataframes

from: https://tutswiki.com/pandas-cookbook/chapter3/

In [2]:
# The usual preamble
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [3]:
plt.rcParams['figure.figsize'] = (15, 5)

In [4]:
complaints = pd.read_csv('311-service-requests.csv')

/home/lswork/miniconda3/envs/bc2019/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [5]:
complaints[:5]

Unique Key            Created Date             Closed Date Agency  \
0    26589651  10/31/2013 02:08:41 AM                     NaN   NYPD   
1    26593698  10/31/2013 02:01:04 AM                     NaN   NYPD   
2    26594139  10/31/2013 02:00:24 AM  10/31/2013 02:40:32 AM   NYPD   
3    26595721  10/31/2013 01:56:23 AM  10/31/2013 02:21:48 AM   NYPD   
4    26590930  10/31/2013 01:53:44 AM                     NaN  DOHMH   

                               Agency Name           Complaint Type  \
0          New York City Police Department  Noise - Street/Sidewalk   
1          New York City Police Department          Illegal Parking   
2          New York City Police Department       Noise - Commercial   
3          New York City Police Department          Noise - Vehicle   
4  Department of Health and Mental Hygiene                   Rodent   

                     Descriptor        Location Type Incident Zip  \
0                  Loud Talking      Street/Sidewalk        11432   
1  Commercial Overnight Parking      Street/Sidewalk        11378   
2              Loud Music/Party  Club/Bar/Restaurant        10032   
3                Car/Truck Horn      Street/Sidewalk        10023   
4  Condition Attracting Rodents           Vacant Lot        10027   

   Incident Address  ... Bridge Highway Name Bridge Highway Direction  \
0  90-03 169 STREET  ...                 NaN                      NaN   
1         58 AVENUE  ...                 NaN                      NaN   
2     4060 BROADWAY  ...                 NaN                      NaN   
3    WEST 72 STREET  ...                 NaN                      NaN   
4   WEST 124 STREET  ...                 NaN                      NaN   

  Road Ramp Bridge Highway Segment Garage Lot Name Ferry Direction  \
0       NaN                    NaN             NaN             NaN   
1       NaN                    NaN             NaN             NaN   
2       NaN                    NaN             NaN             NaN   
3       NaN                    NaN             NaN             NaN   
4       NaN                    NaN             NaN             NaN   

  Ferry Terminal Name   Latitude  Longitude  \
0                 NaN  40.708275 -73.791604   
1                 NaN  40.721041 -73.909453   
2                 NaN  40.843330 -73.939144   
3                 NaN  40.778009 -73.980213   
4                 NaN  40.807691 -73.947387   

                                   Location  
0   (40.70827532593202, -73.79160395779721)  
1  (40.721040535628305, -73.90945306791765)  
2   (40.84332975466513, -73.93914371913482)  
3    (40.7780087446372, -73.98021349023975)  
4   (40.80769092704951, -73.94738703491433)  

[5 rows x 52 columns]

In [9]:
# Selecting only noise complaints
complaints['Complaint Type'] == 'Noise - Street/Sidewalk'

0          True
1         False
2         False
3         False
4         False
          ...  
111064    False
111065    False
111066     True
111067    False
111068    False
Name: Complaint Type, Length: 111069, dtype: bool

In [12]:
# when we index df with this array, we just get the raw
# where our boolean array evaluated to True
# row filtering by a boolean array needs that the 
# length or df index must be the same as the boolean array
is_noise = complaints['Complaint Type'] == 'Noise - Street/Sidewalk'

In [13]:
complaints[is_noise]

Unique Key            Created Date             Closed Date Agency  \
0         26589651  10/31/2013 02:08:41 AM                     NaN   NYPD   
16        26594086  10/31/2013 12:54:03 AM  10/31/2013 02:16:39 AM   NYPD   
25        26591573  10/31/2013 12:35:18 AM  10/31/2013 02:41:35 AM   NYPD   
28        26594085  10/31/2013 12:32:08 AM                     NaN   NYPD   
31        26595564  10/31/2013 12:30:36 AM                     NaN   NYPD   
...            ...                     ...                     ...    ...   
111044    26426096  10/04/2013 12:14:09 AM  10/04/2013 01:03:46 AM   NYPD   
111048    26430030  10/04/2013 12:12:07 AM  10/04/2013 02:45:24 AM   NYPD   
111054    26426060  10/04/2013 12:06:39 AM  10/04/2013 12:31:16 AM   NYPD   
111059    26429040  10/04/2013 12:04:52 AM  10/04/2013 03:01:04 AM   NYPD   
111066    26428987  10/04/2013 12:00:45 AM  10/04/2013 01:25:01 AM   NYPD   

                            Agency Name           Complaint Type  \
0       New York City Police Department  Noise - Street/Sidewalk   
16      New York City Police Department  Noise - Street/Sidewalk   
25      New York City Police Department  Noise - Street/Sidewalk   
28      New York City Police Department  Noise - Street/Sidewalk   
31      New York City Police Department  Noise - Street/Sidewalk   
...                                 ...                      ...   
111044  New York City Police Department  Noise - Street/Sidewalk   
111048  New York City Police Department  Noise - Street/Sidewalk   
111054  New York City Police Department  Noise - Street/Sidewalk   
111059  New York City Police Department  Noise - Street/Sidewalk   
111066  New York City Police Department  Noise - Street/Sidewalk   

              Descriptor    Location Type Incident Zip       Incident Address  \
0           Loud Talking  Street/Sidewalk        11432       90-03 169 STREET   
16      Loud Music/Party  Street/Sidewalk        10310    173 CAMPBELL AVENUE   
25          Loud Talking  Street/Sidewalk        10312      24 PRINCETON LANE   
28          Loud Talking  Street/Sidewalk        10026    121 WEST 116 STREET   
31      Loud Music/Party  Street/Sidewalk        11236               AVENUE J   
...                  ...              ...          ...                    ...   
111044      Loud Talking  Street/Sidewalk        10032    539 WEST 162 STREET   
111048      Loud Talking  Street/Sidewalk        10027  215 WEST 131ST STREET   
111054      Loud Talking  Street/Sidewalk        11224   4823 BEACH 48 STREET   
111059      Loud Talking  Street/Sidewalk        10003            99 2 AVENUE   
111066      Loud Talking  Street/Sidewalk        10016     344 EAST 28 STREET   

        ... Bridge Highway Name Bridge Highway Direction Road Ramp  \
0       ...                 NaN                      NaN       NaN   
16      ...                 NaN                      NaN       NaN   
25      ...                 NaN                      NaN       NaN   
28      ...                 NaN                      NaN       NaN   
31      ...                 NaN                      NaN       NaN   
...     ...                 ...                      ...       ...   
111044  ...                 NaN                      NaN       NaN   
111048  ...                 NaN                      NaN       NaN   
111054  ...                 NaN                      NaN       NaN   
111059  ...                 NaN                      NaN       NaN   
111066  ...                 NaN                      NaN       NaN   

       Bridge Highway Segment Garage Lot Name Ferry Direction  \
0                         NaN             NaN             NaN   
16                        NaN             NaN             NaN   
25                        NaN             NaN             NaN   
28                        NaN             NaN             NaN   
31                        NaN             NaN             NaN   
...                       ...             ...             ... 

In [16]:
# we can combine conditions
in_brooklyn = complaints['Borough'] == 'BROOKLYN'
complaints[is_noise & in_brooklyn]

Unique Key            Created Date             Closed Date Agency  \
31        26595564  10/31/2013 12:30:36 AM                     NaN   NYPD   
49        26595553  10/31/2013 12:05:10 AM  10/31/2013 02:43:43 AM   NYPD   
109       26594653  10/30/2013 11:26:32 PM  10/31/2013 12:18:54 AM   NYPD   
236       26591992  10/30/2013 10:02:58 PM  10/30/2013 10:23:20 PM   NYPD   
370       26594167  10/30/2013 08:38:25 PM  10/30/2013 10:26:28 PM   NYPD   
...            ...                     ...                     ...    ...   
111002    26431562  10/04/2013 01:02:45 AM  10/04/2013 04:43:24 AM   NYPD   
111006    26431994  10/04/2013 12:59:57 AM  10/04/2013 04:43:24 AM   NYPD   
111021    26432669  10/04/2013 12:42:45 AM  10/04/2013 06:48:20 AM   NYPD   
111035    26431005  10/04/2013 12:21:04 AM  10/04/2013 01:50:26 AM   NYPD   
111054    26426060  10/04/2013 12:06:39 AM  10/04/2013 12:31:16 AM   NYPD   

                            Agency Name           Complaint Type  \
31      New York City Police Department  Noise - Street/Sidewalk   
49      New York City Police Department  Noise - Street/Sidewalk   
109     New York City Police Department  Noise - Street/Sidewalk   
236     New York City Police Department  Noise - Street/Sidewalk   
370     New York City Police Department  Noise - Street/Sidewalk   
...                                 ...                      ...   
111002  New York City Police Department  Noise - Street/Sidewalk   
111006  New York City Police Department  Noise - Street/Sidewalk   
111021  New York City Police Department  Noise - Street/Sidewalk   
111035  New York City Police Department  Noise - Street/Sidewalk   
111054  New York City Police Department  Noise - Street/Sidewalk   

              Descriptor    Location Type Incident Zip       Incident Address  \
31      Loud Music/Party  Street/Sidewalk        11236               AVENUE J   
49          Loud Talking  Street/Sidewalk        11225     25 LEFFERTS AVENUE   
109     Loud Music/Party  Street/Sidewalk        11222                    NaN   
236         Loud Talking  Street/Sidewalk        11218          DITMAS AVENUE   
370     Loud Music/Party  Street/Sidewalk        11218       126 BEVERLY ROAD   
...                  ...              ...          ...                    ...   
111002  Loud Music/Party  Street/Sidewalk        11230         630 RUGBY ROAD   
111006      Loud Talking  Street/Sidewalk        11230         630 RUGBY ROAD   
111021      Loud Talking  Street/Sidewalk        11249      125 TAYLOR STREET   
111035  Loud Music/Party  Street/Sidewalk        11205  382 WILLOUGHBY AVENUE   
111054      Loud Talking  Street/Sidewalk        11224   4823 BEACH 48 STREET   

        ... Bridge Highway Name Bridge Highway Direction Road Ramp  \
31      ...                 NaN                      NaN       NaN   
49      ...                 NaN                      NaN       NaN   
109     ...                 NaN                      NaN       NaN   
236     ...                 NaN                      NaN       NaN   
370     ...                 NaN                      NaN       NaN   
...     ...                 ...                      ...       ...   
111002  ...                 NaN                      NaN       NaN   
111006  ...                 NaN                      NaN       NaN   
111021  ...                 NaN                      NaN       NaN   
111035  ...                 NaN                      NaN       NaN   
111054  ...                 NaN                      NaN       NaN   

       Bridge Highway Segment Garage Lot Name Ferry Direction  \
31                        NaN             NaN             NaN   
49                        NaN             NaN             NaN   
109                       NaN             NaN             NaN   
236                       NaN             NaN             NaN   
370                       NaN             NaN             NaN   
...                       ...             ...             ... 

In [17]:
# let's take a few columns
complaints[is_noise & in_brooklyn][['Complaint Type', 'Borough', 'Created Date', 'Descriptor']]

Complaint Type   Borough            Created Date  \
31      Noise - Street/Sidewalk  BROOKLYN  10/31/2013 12:30:36 AM   
49      Noise - Street/Sidewalk  BROOKLYN  10/31/2013 12:05:10 AM   
109     Noise - Street/Sidewalk  BROOKLYN  10/30/2013 11:26:32 PM   
236     Noise - Street/Sidewalk  BROOKLYN  10/30/2013 10:02:58 PM   
370     Noise - Street/Sidewalk  BROOKLYN  10/30/2013 08:38:25 PM   
...                         ...       ...                     ...   
111002  Noise - Street/Sidewalk  BROOKLYN  10/04/2013 01:02:45 AM   
111006  Noise - Street/Sidewalk  BROOKLYN  10/04/2013 12:59:57 AM   
111021  Noise - Street/Sidewalk  BROOKLYN  10/04/2013 12:42:45 AM   
111035  Noise - Street/Sidewalk  BROOKLYN  10/04/2013 12:21:04 AM   
111054  Noise - Street/Sidewalk  BROOKLYN  10/04/2013 12:06:39 AM   

              Descriptor  
31      Loud Music/Party  
49          Loud Talking  
109     Loud Music/Party  
236         Loud Talking  
370     Loud Music/Party  
...                  ...  
111002  Loud Music/Party  
111006      Loud Talking  
111021      Loud Talking  
111035  Loud Music/Party  
111054      Loud Talking  

[456 rows x 4 columns]

In [18]:
# Digression about numpy arrays
# type of a column is pd.Series
pd.Series([1, 2, 3])

0    1
1    2
2    3
dtype: int64

In [20]:
# and Pandas Series are Numpy arrays
pd.Series([1, 2, 3]).values

array([1, 2, 3])

In [21]:
np.array([1, 2, 3])

array([1, 2, 3])

In [22]:
# binary array selection uses numpy array
arr = np.array([1, 2, 3])
arr != 2

array([ True, False,  True])

In [23]:
arr[arr != 2]

array([1, 3])

In [24]:
# Which borough has the more noise complaints 
noise_complaints = complaints[is_noise]
noise_complaints['Borough'].value_counts()

MANHATTAN        917
BROOKLYN         456
BRONX            292
QUEENS           226
STATEN ISLAND     36
Unspecified        1
Name: Borough, dtype: int64

In [27]:
# take care integer division in Python 2, here we are OK with Python 3
total_complaints = noise_complaints.sum()
noise_complaints['Borough'].value_counts() / total_complaints


Agency                          NaN
Agency Name                     NaN
BRONX                           NaN
BROOKLYN                        NaN
Borough                         NaN
Bridge Highway Direction        NaN
Bridge Highway Name             NaN
Bridge Highway Segment          NaN
Community Board                 NaN
Complaint Type                  NaN
Created Date                    NaN
Descriptor                      NaN
Due Date                        NaN
Ferry Direction                 NaN
Ferry Terminal Name             NaN
Garage Lot Name                 NaN
Landmark                        NaN
Latitude                        NaN
Location Type                   NaN
Longitude                       NaN
MANHATTAN                       NaN
Park Borough                    NaN
Park Facility Name              NaN
QUEENS                          NaN
Road Ramp                       NaN
STATEN ISLAND                   NaN
School Address                  NaN
School City                 

In [31]:
# I made a mistake below
noise_complaint_counts = noise_complaints['Borough'].value_counts()
complaint_counts = complaints['Borough'].value_counts()
noise_complaint_counts

MANHATTAN        917
BROOKLYN         456
BRONX            292
QUEENS           226
STATEN ISLAND     36
Unspecified        1
Name: Borough, dtype: int64

In [32]:
complaint_counts

BROOKLYN         32890
MANHATTAN        24288
QUEENS           22281
BRONX            19686
Unspecified       7107
STATEN ISLAND     4817
Name: Borough, dtype: int64

In [33]:
noise_complaint_counts/complaint_counts

BRONX            0.014833
BROOKLYN         0.013864
MANHATTAN        0.037755
QUEENS           0.010143
STATEN ISLAND    0.007474
Unspecified      0.000141
Name: Borough, dtype: float64